# Generated by Django 5.1.4 on 2025-01-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='labels',
            field=models.CharField(blank=True, default=list, max_length=255, null=True),
        ),
    ]
