# Generated by Django 5.1.4 on 2025-01-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_testsuite_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='labels',
            field=models.CharField(blank=True, default='[]', max_length=255, null=True),
        ),
    ]
