# Generated by Django 5.1.4 on 2025-01-18 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_testsuite_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional'), ('Regression', 'Regression')], max_length=50)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('labels', models.PositiveIntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.project')),
            ],
        ),
    ]
