# Generated by Django 5.1.4 on 2025-01-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='labels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
