# Generated by Django 5.1.4 on 2025-01-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_requirementtype_testcasepriority_testcasetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='testcase_priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='testcase',
            name='testcase_type',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional'), ('Regression', 'Regression'), ('Integration', 'Integration')], default='Functional', max_length=50),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='priority',
            field=models.CharField(default='Medium', max_length=50),
        ),
    ]
