# Generated by Django 5.1.4 on 2025-01-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_testcase_testcase_priority_testcase_testcase_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='priority',
        ),
        migrations.AddField(
            model_name='testsuite',
            name='testcase',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
