# Generated by Django 5.1.4 on 2025-01-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_testsuite_priority_testsuite_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.CharField(max_length=250),
        ),
    ]
