# Generated by Django 5.1.4 on 2025-01-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_projectinvitation_projectmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvitation',
            name='token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
