# Generated by Django 5.1.4 on 2025-01-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_projectinvitation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='url',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcase_priority',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcase_type',
            field=models.CharField(default='Functional', max_length=50),
        ),
    ]
