# Generated by Django 5.1.4 on 2025-01-27 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_testdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('step_description', models.TextField()),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.testcase')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('test_case', 'step_number')},
            },
        ),
    ]
