# Generated by Django 5.1.4 on 2025-01-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_teststep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teststep',
            old_name='test_case',
            new_name='testcase',
        ),
        migrations.AlterUniqueTogether(
            name='teststep',
            unique_together={('testcase', 'step_number')},
        ),
    ]
